sudo: required
services: 
    - docker

before-install:
    - docker build -t umishra/docker-react -f Dockerfile.dev .
    
script:
    - docker run umishra/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "<bucket-name>"
    bucket_path: "docker"
    on: 
      branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_Access_key:
        secure: $AWS_SECRET_KEY